import type { LeaderRow } from '../types'
import krEtfNames from '../data/krEtfNames.json' with { type: 'json' }

// Korean short names generated by analysis/kr_etf_names.py (KRX when reachable, else Naver Finance). Only KR ETFs are renamed;
// an ETF missing from the map keeps the name the data source supplied.
export function applyKrEtfNames(rows:LeaderRow[],names:Record<string,string>=krEtfNames):LeaderRow[]{
  return rows.map(row=>{
    const korean=row.market==='KR'&&row.asset_class==='ETF'?names[String(row.ticker).toUpperCase()]:undefined
    return korean?{...row,name:korean}:row
  })
}
