import assert from 'node:assert/strict';
import {existsSync,readFileSync} from 'node:fs';

const required=[
  'docs/design/FOLIO_IDENTITY_V2.md',
  'harness/skills/folio-identity/SKILL.md',
  '.agents/skills/folio-identity/SKILL.md',
  '.claude/skills/folio-identity/SKILL.md',
  'plugins/pepper-harness/skills/folio-identity/SKILL.md',
  '.claude/agents/identity-reviewer.md',
  '.codex/agents/identity-reviewer.toml',
  'tests/brand.spec.ts',
  'tests/theme-system.spec.ts',
  'tests/compact-editorial.spec.ts',
  'scripts/generate-b-app-icons.mjs',
  'public/folio-b-xx-light.png',
  'public/folio-b-xx-dark.png',
  'public/folio-b-icon-180.png',
  'public/folio-b-icon-192.png',
  'public/folio-b-icon-512.png',
  'public/folio-b-icon-512-maskable.png',
  'public/folio-b-launch-hero.webp',
  'public/folio-b-motif.webp',
  'public/folio-c-photography.webp'
];
for(const file of required)assert(existsSync(file),`Missing Folio B identity file: ${file}`);

const read=file=>readFileSync(file,'utf8');
const contract=read('docs/harness/CONTRACT.md');
const design=read('docs/design/FOLIO_IDENTITY_V2.md');
const css=read('src/design/folio-identity.css');
const main=read('src/main.tsx');
const app=read('src/App.tsx');
const sidebar=read('src/components/Sidebar.tsx');
const pkg=JSON.parse(read('package.json'));
const manifest=JSON.parse(read('public/manifest.webmanifest'));
const claudePlugin=JSON.parse(read('plugins/pepper-harness/.claude-plugin/plugin.json'));
const codexPlugin=JSON.parse(read('plugins/pepper-harness/.codex-plugin/plugin.json'));
const agentsEntry=read('AGENTS.md');
const claudeEntry=read('CLAUDE.md');

assert(contract.includes('attached column 02 “Sunset Editorial” (B) is the authoritative visual reference'), 'CONTRACT must make the attached B column authoritative.');
assert(design.includes('attached concept board\'s column 02 — “Sunset Editorial” (B)'), 'Design doc must name the B concept board as source of truth.');
assert(design.includes('C remains photography treatment only') || design.includes('C is limited to photography treatment'), 'Design doc must limit C to photography treatment.');
assert(css.includes('B EXACT LOCK'), 'Exact B CSS lock is missing.');
assert(css.includes('Inter,"Neue Haas Grotesk Text"'), 'B typography stack drifted.');
assert(main.includes("import './design/folio-identity.css'"), 'Folio identity stylesheet is not loaded.');
assert(!existsSync('src/design/robinhood.css'), 'Superseded robinhood.css must stay removed.');
assert(!existsSync('scripts/generate-folio-icons.mjs'), 'Generic icon generator must stay removed once exact B artwork is committed.');
assert(!existsSync('public/folio-b-wordmark-light.webp')&&!existsSync('public/folio-b-wordmark-dark.webp'),'Noisy screenshot-crop wordmarks must stay removed.');
assert(!pkg.scripts?.predev&&!pkg.scripts?.prebuild, 'Exact B artwork must not be regenerated by npm lifecycle scripts.');
const iconBuild=read('scripts/generate-b-app-icons.mjs');
assert(pkg.scripts?.build?.startsWith('node scripts/generate-b-app-icons.mjs &&'),'Build must render the corrected B app-icon family before Vite.');
assert(iconBuild.includes('MARK_WIDTH_RATIO=0.3125')&&iconBuild.includes('MARK_ASPECT=1.72'),'B app-icon xx scale/aspect drifted from the corrected concept-B geometry.');

assert(sidebar.includes('folio-wordmark-text')&&sidebar.includes('>Folio</span>'),'Sidebar must render the B Folio text lockup.');
for(const asset of ['folio-b-xx-light.png','folio-b-xx-dark.png'])assert(sidebar.includes(asset),`Sidebar B xx mark missing ${asset}`);
assert(css.includes('.folio-wordmark-text')&&css.includes('font-family:Inter'),'B wordmark typography contract is missing.');
for(const asset of ['folio-b-launch-hero.webp','folio-b-motif.webp','folio-c-photography.webp'])assert(app.includes(asset),`App identity placement missing ${asset}`);
for(const label of ["system:'System'","light:'Light'","dark:'Dark'"])assert(sidebar.includes(label),`Theme mode missing: ${label}`);
assert.equal(pkg.scripts?.['test:identity'],'playwright test tests/brand.spec.ts tests/theme-system.spec.ts tests/compact-editorial.spec.ts tests/compact-titlebar.spec.ts tests/discovery.spec.ts','test:identity script drifted.');
assert(agentsEntry.includes('docs/design/FOLIO_IDENTITY_V2.md')&&agentsEntry.includes('folio-identity'),'AGENTS.md must route identity work through the design doc and skill.');
assert(claudeEntry.includes('docs/design/FOLIO_IDENTITY_V2.md')&&claudeEntry.includes('folio-identity'),'CLAUDE.md must route identity work through the design doc and skill.');
assert.equal(claudePlugin.version,'1.2.0','Claude harness plugin version must match exact-B bundle.');
assert.equal(codexPlugin.version,'1.2.0','Codex harness plugin version must match exact-B bundle.');

const expectedIcons=[
  './folio-b-icon-192.png',
  './folio-b-icon-512.png',
  './folio-b-icon-512-maskable.png'
];
assert.deepEqual(manifest.icons.map(icon=>icon.src),expectedIcons,'Manifest must use only exact B app icons.');
assert.equal(manifest.background_color,'#f4f1ec','Manifest paper color must match B editorial paper.');
assert.equal(manifest.theme_color,'#f4f1ec','Manifest theme color must match B editorial paper.');

for(const file of ['app/index.html','public/sw.js','src/components/InstallApp.tsx','.github/workflows/deploy.yml']){
  const content=read(file);
  assert(!content.includes('folio-app-icon-'),`Stale punch-card icon reference in ${file}`);
  assert(!content.includes('folio-identity-'),`Superseded generated identity reference in ${file}`);
  assert(content.includes('folio-b-icon-'),`Exact B icon reference missing in ${file}`);
}

const deployWorkflow=read('.github/workflows/deploy.yml');
for(const asset of [
  'folio-b-xx-light.png',
  'folio-b-xx-dark.png',
  'folio-b-launch-hero.webp',
  'folio-b-motif.webp',
  'folio-c-photography.webp'
]){
  assert(deployWorkflow.includes(asset),`Pages root sync missing active identity asset: ${asset}`);
}
for(const file of ['app/index.html','src/components/Sidebar.tsx']){
  const content=read(file);
  assert(!content.includes('folio-wordmark.webp'),`Legacy wordmark reference in active UI: ${file}`);
  assert(!content.includes('folio-icon.webp'),`Legacy emblem reference in active UI: ${file}`);
}

console.log('Folio exact Sunset Editorial B identity invariants passed.');
